qerror: expose a function to format an error
This will let Error share the QError human formatting.  This is only used for
HMP.

Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>