error: Let converted handlers print in human monitor
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-37-git-send-email-armbru@redhat.com>
Patchwork-id: 8229
O-Subject: [PATCH 36/66] error: Let converted handlers print in human monitor
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

While fully converted handlers are not supposed to print anything when
running in a QMP monitor, they are free to print in a human monitor.
For instance, device_add (not yet converted) prints help, and will
continue to do so after conversion.

Moreover, utility functions converted to QError should remain usable
from unconverted handlers.

Two problems:

* handler_audit() complains when a converted handler prints.  Limit
  that to QMP monitors.

* With QMP, handlers need to pass the error object by way of
  monitor_set_error().  However, we do that both for QMP and for the
  human monitor.  The human monitor prints the error object after the
  handler returns.  If the handler prints anything else, that output
  "overtakes" the error message.

  Limit use of monitor_set_error() to QMP monitors.  Update
  handler_audit() accordingly.
(cherry picked from commit cde0fc7544ca590c83f349d4dcccf375d55d6042)
---
 monitor.c    |   80 ++++++++++++++++++++++++++-------------------------------
 qemu-error.c |    2 +-
 2 files changed, 38 insertions(+), 44 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>