error: Rename qemu_error_new() to qerror_report()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <m3633lxiow.fsf_-_@blackfin.pond.sub.org>
Patchwork-id: 8755
O-Subject: [PATCH 25/66 v2] error: Rename qemu_error_new() to qerror_report()
Bugzilla: 579470
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>

(cherry picked from commit ab5b027ee645f26320379d1d80cd96fdc944ecb5)

Conflicts:

	monitor.c

spice.c manually backported.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
---
v2: new spice.c, trivially rediff the rest

 hw/qdev.c    |    2 +-
 monitor.c    |   82 +++++++++++++++++++++++++++++-----------------------------
 qemu-error.c |    6 ++--
 qemu-error.h |   10 +++---
 spice.c      |   14 +++++-----
 5 files changed, 57 insertions(+), 57 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>