error: Track locations on command line
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-31-git-send-email-armbru@redhat.com>
Patchwork-id: 8218
O-Subject: [PATCH 30/66] error: Track locations on command line
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

New LOC_CMDLINE.  Use it for tracking option with argument in
lookup_opt().  We now report errors like this

    qemu: -device smbus-eeprom: Did not find I2C bus for smbus-eeprom
(cherry picked from commit 0f0bc3f1d526924ef4a75ad25dd0ec3771a66496)
---
 qemu-error.c |   20 ++++++++++++++++++++
 qemu-error.h |    3 ++-
 vl.c         |    9 +++++----
 3 files changed, 27 insertions(+), 5 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>