error: Trim includes after "Move qemu_error & friends..."
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-62-git-send-email-armbru@redhat.com>
Patchwork-id: 8228
O-Subject: [PATCH 61/66] error: Trim includes after "Move qemu_error &
	friends..."
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Missed in commit 2f792016.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
(cherry picked from commit 9f59b566a6569be148df0f2eb912b11c9d030deb)
---
 hw/qdev-properties.c |    1 +
 monitor.c            |    2 --
 sysemu.h             |    2 --
 3 files changed, 1 insertions(+), 4 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>