error: Convert do_device_add() to QError
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-55-git-send-email-armbru@redhat.com>
Patchwork-id: 8267
O-Subject: [PATCH 54/66] error: Convert do_device_add() to QError
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Conversion to QObject is still missing.
(cherry picked from commit 0204276bc9108d6a927f4267b87338950a538671)
---
 hw/qdev.c |   19 +++++++++----------
 1 files changed, 9 insertions(+), 10 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>