error: Don't abuse qemu_error() for non-error in qdev_device_help()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-22-git-send-email-armbru@redhat.com>
Patchwork-id: 8235
O-Subject: [PATCH 21/66] error: Don't abuse qemu_error() for non-error in
	qdev_device_help()
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

qdev_device_help() prints device information with qemu_error().  A
later commit will make qemu_error() print additional stuff that is
only appropriate for proper errors, and then this will break.  Use
error_printf() instead.

While there, simplify: instead of printing a buffer filled by
qdev_print_devinfo() in one go, make qdev_print_devinfo() print it.
(cherry picked from commit 8a9662ca67c7ecb6cc3d9b2055438bacbf61682e)
---
 hw/qdev.c |   31 ++++++++++---------------------
 1 files changed, 10 insertions(+), 21 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>