error: Move qerror_report() from qemu-error.[ch] to qerror.[ch]
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-67-git-send-email-armbru@redhat.com>
Patchwork-id: 8254
O-Subject: [PATCH 66/66] error: Move qerror_report() from qemu-error.[ch] to
	qerror.[ch]
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
(cherry picked from commit 0167f772d1505b79f2db2f1d3ccad54f2cbe5de1)
---
 qemu-error.c |   18 ------------------
 qemu-error.h |    6 ------
 qerror.c     |   20 ++++++++++++++++++++
 qerror.h     |    5 +++++
 4 files changed, 25 insertions(+), 24 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>