error: New error_printf_unless_qmp()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-49-git-send-email-armbru@redhat.com>
Patchwork-id: 8222
O-Subject: [PATCH 48/66] error: New error_printf_unless_qmp()
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit aa924ae7306f18f258c48f070c0d06215f157d0f)
---
 qemu-error.c |   11 +++++++++++
 qemu-error.h |    2 ++
 2 files changed, 13 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>