error: New QERR_DEVICE_NO_BUS
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-47-git-send-email-armbru@redhat.com>
Patchwork-id: 8256
O-Subject: [PATCH 46/66] error: New QERR_DEVICE_NO_BUS
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 07574baf7b714a10e35b716b0eb6ede197adfca7)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>