error: New QERR_BAD_BUS_FOR_DEVICE
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-50-git-send-email-armbru@redhat.com>
Patchwork-id: 8224
O-Subject: [PATCH 49/66] error: New QERR_BAD_BUS_FOR_DEVICE
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 56e9f56309b7c77dfb328dbf450d04fd54ce4542)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>