error: New QERR_PROPERTY_VALUE_BAD
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-40-git-send-email-armbru@redhat.com>
Patchwork-id: 8261
O-Subject: [PATCH 39/66] error: New QERR_PROPERTY_VALUE_BAD
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 06b4a703e0e87034a8b122f6ffc50c732e7ceddd)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>