QError: Improve QERR_QMP_BAD_INPUT_OBJECT desc
RH-Author: Luiz Capitulino <lcapitulino@redhat.com>
Message-id: <1273253840-25924-4-git-send-email-lcapitulino@redhat.com>
Patchwork-id: 9115
O-Subject: [PATCH 3/4] QError: Improve QERR_QMP_BAD_INPUT_OBJECT desc
Bugzilla: 573578
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
(cherry picked from commit abaf2f52716625d4b1e29204cab644ed656504cf)
---
 qerror.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>