QError: New QERR_QMP_BAD_INPUT_OBJECT_MEMBER
RH-Author: Luiz Capitulino <lcapitulino@redhat.com>
Message-id: <1273253840-25924-2-git-send-email-lcapitulino@redhat.com>
Patchwork-id: 9113
O-Subject: [PATCH 1/4] QError: New QERR_QMP_BAD_INPUT_OBJECT_MEMBER
Bugzilla: 573578
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
(cherry picked from commit 7dfb61238a472acf6fb48d9a444564b9b99a4b56)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>