error: New QERR_NO_BUS_FOR_DEVICE
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-53-git-send-email-armbru@redhat.com>
Patchwork-id: 8258
O-Subject: [PATCH 52/66] error: New QERR_NO_BUS_FOR_DEVICE
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit fab5767f90c96194f918d39af683fff3d9ea421a)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>