error: Don't abuse qemu_error() for non-error in scsi_hot_add()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-24-git-send-email-armbru@redhat.com>
Patchwork-id: 8204
O-Subject: [PATCH 23/66] error: Don't abuse qemu_error() for non-error in
	scsi_hot_add()
Bugzilla: 579470
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Commit 30d335d6 converted an informational message from
monitor_printf() to qemu_error(), probably because the latter doesn't
need a mon argument.  A later commit will make qemu_error() print
additional stuff that is only appropriate for proper errors, and then
this will break.  Clean it up.
(cherry picked from commit 6fdb03d58c614e0097d80ed130c19dcc393f7421)
---
 hw/pci-hotplug.c |   10 ++++++----
 1 files changed, 6 insertions(+), 4 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>