error: Move qemu_error & friends into their own header
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-20-git-send-email-armbru@redhat.com>
Patchwork-id: 8216
O-Subject: [PATCH 19/66] error: Move qemu_error & friends into their own header
Bugzilla: 579470
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 2f7920166d1aa402104d7b30d0225e71588f91f9)

hw/device-assignment.c manually backported.
---
 hw/device-assignment.c |    2 +-
 hw/scsi-bus.c          |    2 +-
 hw/scsi-disk.c         |    3 +--
 hw/scsi-generic.c      |    1 +
 hw/usb-serial.c        |    1 +
 hw/virtio-net.c        |    1 +
 hw/virtio-pci.c        |    2 +-
 monitor.h              |    1 +
 net/dump.c             |    1 +
 net/socket.c           |    2 +-
 net/tap-linux.c        |    1 +
 net/tap.c              |    1 +
 qemu-config.c          |    1 +
 qemu-error.h           |   12 ++++++++++++
 qemu-tool.c            |    2 +-
 qerror.c               |    2 +-
 sysemu.h               |    8 --------
 17 files changed, 27 insertions(+), 16 deletions(-)
 create mode 100644 qemu-error.h

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>