error: New QERR_PROPERTY_VALUE_IN_USE
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-41-git-send-email-armbru@redhat.com>
Patchwork-id: 8246
O-Subject: [PATCH 40/66] error: New QERR_PROPERTY_VALUE_IN_USE
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 9c5eff958d527d1803114a6f78d086fb313b9bd2)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>