error: Simplify error sink setup
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-19-git-send-email-armbru@redhat.com>
Patchwork-id: 8234
O-Subject: [PATCH 18/66] error: Simplify error sink setup
Bugzilla: 579470
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

qemu_error_sink can either point to a monitor or a file.  In practice,
it always points to the current monitor if we have one, else to
stderr.  Simply route errors to the current monitor or else to stderr,
and remove qemu_error_sink along with the functions to control it.

Actually, the old code switches the sink slightly later, in
handle_user_command() and handle_qmp_command(), than it gets switched
now, implicitly, by setting the current monitor in monitor_read() and
monitor_control_read().  Likewise, it switches back slightly earlier
(same places).  Doesn't make a difference, because there are no calls
of qemu_error() in between.
(cherry picked from commit 6e4f984cb9474db99bf4e3998ff86cdb9ed02380)
---
 monitor.c    |    6 ----
 qemu-error.c |   76 +++++++---------------------------------------------------
 sysemu.h     |    3 --
 vl.c         |    1 -
 4 files changed, 9 insertions(+), 77 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>