error: New QERR_PROPERTY_NOT_FOUND
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-39-git-send-email-armbru@redhat.com>
Patchwork-id: 8226
O-Subject: [PATCH 38/66] error: New QERR_PROPERTY_NOT_FOUND
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit c58a35f8e32af621fab2b4f9c868f47971f67e59)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>