error: Move qemu_error() & friends from monitor.c to own file
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-18-git-send-email-armbru@redhat.com>
Patchwork-id: 8253
O-Subject: [PATCH 17/66] error: Move qemu_error() & friends from monitor.c to
	own file
Bugzilla: 579470
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

They're about reporting errors, not about the monitor.
(cherry picked from commit b4a51f7f5d4855d1af7eb6ce6c6f79bd24d1d5a8)
---
 Makefile.target |    1 +
 monitor.c       |   89 -----------------------------------------------------
 qemu-error.c    |   92 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 3 files changed, 93 insertions(+), 89 deletions(-)
 create mode 100644 qemu-error.c

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>