error: Trim includes in qerror.c
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-63-git-send-email-armbru@redhat.com>
Patchwork-id: 8255
O-Subject: [PATCH 62/66] error: Trim includes in qerror.c
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
(cherry picked from commit c8bfe7db2761c37136b550eb3bccd221dc7226cd)
---
 qerror.c |    2 --
 1 files changed, 0 insertions(+), 2 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>