error: Include the program name in error messages to stderr
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-28-git-send-email-armbru@redhat.com>
Patchwork-id: 8257
O-Subject: [PATCH 27/66] error: Include the program name in error messages to
	stderr
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 65abca0a3441fb47024553e7676f6f3eef685a32)
---
 qemu-error.c |   20 +++++++++++++++++++-
 qemu-error.h |    1 +
 vl.c         |    2 ++
 3 files changed, 22 insertions(+), 1 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>