error: Polish human-readable error descriptions
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-38-git-send-email-armbru@redhat.com>
Patchwork-id: 8252
O-Subject: [PATCH 37/66] error: Polish human-readable error descriptions
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

From: Markus Armbruster <armbru@pond.sub.org>

Also put error definitions in alphabetical order
(cherry picked from commit fc5469d87b54bfbe06b76a9bb9da6589c326e0b2)

Conflicts:

	qerror.h

Note: merge puts error definitions out of in alphabetical again.
---
 qerror.c |   28 ++++++++++++++--------------
 qerror.h |   14 +++++++-------
 2 files changed, 21 insertions(+), 21 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>