error: Convert qemu_opts_create() to QError
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1271329198-13424-5-git-send-email-armbru@redhat.com>
Patchwork-id: 8631
O-Subject: [RHEL-6 KVM PATCH 04/12] error: Convert qemu_opts_create() to QError
Bugzilla: 559670
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>

Fixes device_add to report duplicate ID properly in QMP, as
DuplicateId instead of UndefinedError.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
---
 qemu-option.c |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>