error: New QERR_BUS_NO_HOTPLUG
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-51-git-send-email-armbru@redhat.com>
Patchwork-id: 8215
O-Subject: [PATCH 50/66] error: New QERR_BUS_NO_HOTPLUG
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 8eae73b5d7085b0f9b087033c328fdbbbcc6271d)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>