error: New QERR_BUS_NOT_FOUND
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-45-git-send-email-armbru@redhat.com>
Patchwork-id: 8212
O-Subject: [PATCH 44/66] error: New QERR_BUS_NOT_FOUND
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 7bbd823701cf4447b5c23430f1ad78ce501793b4)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>