error: New QERR_DEVICE_INIT_FAILED
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-52-git-send-email-armbru@redhat.com>
Patchwork-id: 8219
O-Subject: [PATCH 51/66] error: New QERR_DEVICE_INIT_FAILED
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

From: Markus Armbruster <armbru@pond.sub.org>

(cherry picked from commit 4d9a1a15214c01dcbff2d7c02cef027e80442d79)

Conflicts:

	qerror.c
	qerror.h
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>