block.c: fix warning with _FORTIFY_SOURCE
RH-Author: Juan Quintela <quintela@redhat.com>
Message-id: <733691e6d52f0e4dccf5416f767412cf1af85b9b.1267743950.git.quintela@redhat.com>
Patchwork-id: 7534
O-Subject: [PATCH 06/32] block.c: fix warning with _FORTIFY_SOURCE
Bugzilla: 567099
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Amit Shah <amit.shah@redhat.com>
RH-Acked-by: Marcelo Tosatti <mtosatti@redhat.com>

From: Kirill A. Shutemov <kirill@shutemov.name>

CC    block.o
cc1: warnings being treated as errors
block.c: In function 'bdrv_open2':
block.c:400: error: ignoring return value of 'realpath', declared with attribute warn_unused_result

Signed-off-by: Kirill A. Shutemov <kirill@shutemov.name>
Signed-off-by: Blue Swirl <blauwirbel@gmail.com>
(cherry picked from commit 114cdfa908520ccc624fc8e5409252dc6e980f8a)

aio_signal_handler() don't exist anymore, dropping that chunk.

Signed-off-by: Juan Quintela <quintela@redhat.com>
---
 block.c |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>