error: Track locations in configuration files
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-29-git-send-email-armbru@redhat.com>
Patchwork-id: 8233
O-Subject: [PATCH 28/66] error: Track locations in configuration files
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

New LOC_FILE.  Use it for tracking file name and line number in
qemu_config_parse().  We now report errors like

    qemu:foo.conf:42: Did not find I2C bus for smbus-eeprom

In particular, gems like this message:

    -device: no driver specified

become almost nice now:

    qemu:foo.conf:44: -device: no driver specified

(A later commit will get rid of the bogus -device:)
(cherry picked from commit cf5a65aaaf3e9382e50df550ba049a1c8691a5dd)
---
 qemu-config.c |   28 +++++++++++++++++-----------
 qemu-config.h |    2 +-
 qemu-error.c  |   20 ++++++++++++++++++++
 qemu-error.h  |    3 ++-
 vl.c          |   14 +++++++++-----
 5 files changed, 49 insertions(+), 18 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>