error: Link qemu-img, qemu-nbd, qemu-io with qemu-error.o
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-66-git-send-email-armbru@redhat.com>
Patchwork-id: 8231
O-Subject: [PATCH 65/66] error: Link qemu-img, qemu-nbd,
	qemu-io with qemu-error.o
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

From: Markus Armbruster <armbru@pond.sub.org>

The location tracking interface is used by code shared with qemi-img,
qemu-nbd and qemu-io, so it needs to be available there.  Commit
827b0813 provides it in a rather hamfisted way: it adds a dummy
implementation to qemu-tool.c.

It's cleaner to provide the real thing, and put a few more dummy
monitor functions into qemu-tool.c.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
(cherry picked from commit 526f0ac1538378a561b629cb2f99a0349d48bc2f)

Conflicts:

	Makefile
---
 Makefile    |    6 +++---
 qemu-tool.c |   49 +++++++++++++++----------------------------------
 2 files changed, 18 insertions(+), 37 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>