error: Make use of error_set_progname() optional
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-65-git-send-email-armbru@redhat.com>
Patchwork-id: 8243
O-Subject: [PATCH 64/66] error: Make use of error_set_progname() optional
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
(cherry picked from commit 6627f64510b622912d35ced2771583e03b1f155f)
---
 qemu-error.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>