QError: New QERR_OPEN_FILE_FAILED
RH-Author: Luiz Capitulino <lcapitulino@redhat.com>
Message-id: <1268923406-3785-3-git-send-email-lcapitulino@redhat.com>
Patchwork-id: 7885
O-Subject: [PATCH 2/6] QError: New QERR_OPEN_FILE_FAILED
Bugzilla: 574642
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>

From: Markus Armbruster <armbru@redhat.com>

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>
(cherry picked from commit 3da2c8081478ee11c7f3aebcbf42680c975b0712)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>