QError: New QERR_INVALID_CPU_INDEX
RH-Author: Luiz Capitulino <lcapitulino@redhat.com>
Message-id: <1268923406-3785-6-git-send-email-lcapitulino@redhat.com>
Patchwork-id: 7888
O-Subject: [PATCH 5/6] QError: New QERR_INVALID_CPU_INDEX
Bugzilla: 574642
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>

From: Markus Armbruster <armbru@redhat.com>

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>
(cherry picked from commit 64a34bb14c0e358a6b2f14805e59ef25bf62d6d5)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>