error: Trim includes after "Infrastructure to track locations..."
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-64-git-send-email-armbru@redhat.com>
Patchwork-id: 8262
O-Subject: [PATCH 63/66] error: Trim includes after "Infrastructure to track
	locations..."
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

Missed in commit 827b0813.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
(cherry picked from commit fc2377ea29d11eb7ccc881b60ced7782fbc60443)
---
 monitor.h |    1 -
 1 files changed, 0 insertions(+), 1 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>