error: New QERR_DEVICE_MULTIPLE_BUSSES
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-46-git-send-email-armbru@redhat.com>
Patchwork-id: 8263
O-Subject: [PATCH 45/66] error: New QERR_DEVICE_MULTIPLE_BUSSES
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 1ae787184025b7e890a666e0041024a3d92529ce)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>