error: Use QERR_INVALID_PARAMETER_VALUE instead of QERR_INVALID_PARAMETER
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1271329198-13424-9-git-send-email-armbru@redhat.com>
Patchwork-id: 8629
O-Subject: [RHEL-6 KVM PATCH 08/12] error: Use QERR_INVALID_PARAMETER_VALUE
	instead of QERR_INVALID_PARAMETER
Bugzilla: 559670
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>

Signed-off-by: Markus Armbruster <armbru@redhat.com>
---
 hw/qdev.c |    2 +-
 monitor.c |    6 ++++--
 2 files changed, 5 insertions(+), 3 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>