error: New QERR_PROPERTY_VALUE_NOT_FOUND
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-42-git-send-email-armbru@redhat.com>
Patchwork-id: 8240
O-Subject: [PATCH 41/66] error: New QERR_PROPERTY_VALUE_NOT_FOUND
Bugzilla: 579470
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit 84745d68e7338271f0f7ec567ab52abf20a0ce9c)
---
 qerror.c |    4 ++++
 qerror.h |    3 +++
 2 files changed, 7 insertions(+), 0 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>