error: New error_printf() and error_vprintf()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-21-git-send-email-armbru@redhat.com>
Patchwork-id: 8209
O-Subject: [PATCH 20/66] error: New error_printf() and error_vprintf()
Bugzilla: 579470
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

(cherry picked from commit ba0fe87acd8937d403f60da63290aadb0b84827e)
---
 qemu-error.c |   49 ++++++++++++++++++++++++++++++++++++++++++-------
 qemu-error.h |   14 ++++++++++++++
 2 files changed, 56 insertions(+), 7 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>