error: Don't abuse qemu_error() for non-error in qbus_find()
RH-Author: Markus Armbruster <armbru@redhat.com>
Message-id: <1270041921-28969-23-git-send-email-armbru@redhat.com>
Patchwork-id: 8232
O-Subject: [PATCH 22/66] error: Don't abuse qemu_error() for non-error in
	qbus_find()
Bugzilla: 579470
RH-Acked-by: Juan Quintela <quintela@redhat.com>
RH-Acked-by: Kevin Wolf <kwolf@redhat.com>
RH-Acked-by: Luiz Capitulino <lcapitulino@redhat.com>

qbus_find() adds an informational line to error messages, and prints
both lines with one qemu_error().  Use error_printf() for the
informational line instead.

While there, simplify: instead of printing buffers filled by
qbus_list_bus() and qbus_list_dev() in one go, make them print it.
(cherry picked from commit 53db16b5b056e7b38384014c1bce75116ed27044)
---
 hw/qdev.c |   37 +++++++++++++++++--------------------
 1 files changed, 17 insertions(+), 20 deletions(-)

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>